### ISSUE TITLE
Doesn't work if /etc/bash_completion is missing

### ISSUE THREAD

**Issue by SmartFinn** [3v1n0/zsh-bash-completions-fallback#1]
If you want to check if one of `bash_completion` exists the correct operator it this statement is `&&`:

```sh
if ! [ -f /etc/bash_completion ] &&
   ! [ -f "$_bash_completions/bash_completion" ]; then
   return 1;
fi
```

But I really don't understand why it needed at all. Just check that `bash-completion/completions` directory exists. It should be enough.

**Comment by 3v1n0** [comment]
Well, in both the zsh and sh scripts we assume that the completions can be in both locations, so I think be alternative is fine here, no?

**Comment by SmartFinn** [comment]
Okay, the main issue is why do you need both of these files? Nothing bad happens if one of them will be missing. Fedora has not /etc/bash_completion file and the plugin doesn't load without fix above.
