### ISSUE TITLE
No complete menu when lazy load enabled

### ISSUE THREAD

**Issue by SmartFinn** [3v1n0/zsh-bash-completions-fallback#4]
> >initial double Tab is very annoying to me.

> Weird this should not happen, the first tab should call the normal completion function no?
> It may be a bit slower, but nothing big.

> _Originally posted by @3v1n0 in https://github.com/3v1n0/zsh-bash-completions-fallback/issues/3#issuecomment-637083402_

Yeah, when I executed your plugin in xtrace mode I saw the problem:

![image](https://user-images.githubusercontent.com/819186/83452022-9f05e200-a460-11ea-8b63-50a6786bb27a.png)

After commenting the line https://github.com/3v1n0/zsh-bash-completions-fallback/blob/fec54fb639ff3cce31948a55e84b8a2c50ae8991/zsh-bash-completions-fallback.plugin.zsh#L198 it starts work as expected.

**Comment by 3v1n0** [comment]
Thanks, it was indeed wrong, I introduced that while cleaning up too much :)
