### ISSUE TITLE
[bug] source bash completion prior to zsh completion

### ISSUE THREAD

**Issue by Freed-Wu** [3v1n0/zsh-bash-completions-fallback#6]
python-pip has its bash-completion:
```shell
❯ pacman -Ql python-pip|rg -N /usr/share/bash-completion/completions/pip
python-pip /usr/share/bash-completion/completions/pip
```

And zsh have a completion for pip, too:
```
❯ head -n1 /usr/share/zsh/functions/Completion/Unix/_pip
#compdef -P pip[0-9.]#
```

## Actual

However, if user use this plugin, this plugin will source bash completion not zsh completion.

## Expected

Source zsh completion, only when zsh completion is not found and bash completion exists, source bash completion.

## Completion

If user change the first line of zsh completion:
```
❯ head -n1 /usr/share/zsh/functions/Completion/Unix/_pip
#compdef pip
```

This bug can disappear. I think this plugin don't know `compdef -P` is zsh completion?

Thanks.

**Comment by 3v1n0** [comment]
I suppose this depends on the order you load... We try to be conservative by default, but it all depends whether a completion is defined in the `_comps` array.

**Comment by Freed-Wu** [comment]
> it all depends whether a completion is defined in the _comps array.

Right, `compdef -P pip[0-9.]#` will not add any element to `_comps`

```
❯ print -l $_comps|rg pip
❯
```

It looks like the only method to solve this problem is manual intervention.

How can I tell this plugin not to complete some program (e.g., pip)?

**Comment by Freed-Wu** [comment]
> How can I tell this plugin not to complete some program (e.g., pip)?

Oh, just `compdef _pip pip` in zshrc. Thanks!
