### ISSUE TITLE
bash completion for lftp cannot be loaded by zsh

### ISSUE THREAD

**Issue by Freed-Wu** [3v1n0/zsh-bash-completions-fallback#7]
For other program, such as lftpget (provided by package lftp together with program lftp) can work.

```shell
% lftp -<TAB>
# nothing happens
% bash
$ lftp -<TAB>
-c         -d         -e         -f         --help     --norc     -p         -s         -u         --version
```

**Comment by 3v1n0** [comment]
Is it handled for you?

Check in `_bash_completions_fallback_list_handled_completions | grep ftp`, in my case the completion is handled by zsh itself...

**Comment by Freed-Wu** [comment]
Oh, it is a bug related to ncftp:

```
❯ rg lftp ~/.zcompdump
759:'lftp' '_ncftp'
```

Sorry! :cry:

**Comment by 3v1n0** [comment]
NW, you can override this by defining `ZSH_BASH_COMPLETIONS_FALLBACK_REPLACE_LIST=(lftp)`

**Comment by 3v1n0** [comment]
It's actually working better than the native one to me

**Comment by 3v1n0** [comment]
FYI I've added some debugging command, can be used with something like: https://github.com/3v1n0/zsh-bash-completions-fallback/commit/8383b7effdf80349ae513d5c04525a8fc70f777a
